In [2]:
import torch 
import numpy as np

In [3]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [4]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [5]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [6]:
# Initializing random values for Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

In [7]:
#model that performs matrix multiplication of inputs with weights and then adds bias
def model(x):
    return x @ w.t() + b

In [8]:
#Initial Prediction
preds = model(inputs)
print(preds)

tensor([[ -24.5325, -111.3928],
        [ -23.4997, -140.3286],
        [ -43.5096, -118.2403],
        [ -34.1608, -164.3170],
        [ -11.2445, -103.6636]], grad_fn=<AddBackward0>)


In [9]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [10]:
# Mean Squared Error loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [11]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(30439.3008, grad_fn=<DivBackward0>)


In [12]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()

In [13]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(105.1452, grad_fn=<DivBackward0>)


In [14]:
# Predictions
preds

tensor([[ 59.7462,  68.5480],
        [ 88.1699,  94.9856],
        [101.0871, 149.0946],
        [ 36.8482,  25.1619],
        [102.9994, 116.3148]], grad_fn=<AddBackward0>)

In [15]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])